const SET_ERROR = 'constants/SET_ERROR'
const SET_HAS_MORE = 'constants/SET_HAS_MORE'
const SET_IS_LOADING = 'constants/SET_IS_LOADING'
const SET_POKEMONS = 'constants/SET_POKEMONS'
const SET_OFFSET = 'constants/SET_OFFSET'
const SET_CATCHED = 'constants/SET_CATCHED'
const SET_GAME_ACTIVE = 'constants/SET_GAME_ACTIVE'
const SET_POKEMON_ENCOUNTERED = 'constants/SET_POKEMON_ENCOUNTERED'

export { 
    SET_ERROR,
    SET_HAS_MORE,
    SET_IS_LOADING,
    SET_POKEMONS,
    SET_OFFSET,
    SET_CATCHED,
    SET_GAME_ACTIVE,
    SET_POKEMON_ENCOUNTERED
}